DBS-3596 - POC: PostgresSQL Deployment Flow - resolve comments

diff --git a/server/resources/pgsql/templates/standalone-deployment.yaml b/server/resources/pgsql/templates/standalone-deployment.yaml
--- a/server/resources/pgsql/templates/standalone-deployment.yaml
+++ b/server/resources/pgsql/templates/standalone-deployment.yaml
@@ -144,13 +144,6 @@ Resources:
               fi
             }
 
-            # Increase shared memory limits
-            echo "kernel.shmmax = 68719476736" | sudo tee /etc/sysctl.d/99-postgresql.conf
-            echo "kernel.shmall = 4294967296" | sudo tee -a /etc/sysctl.d/99-postgresql.conf
-            sudo sysctl --system
-            
-            check_status "Failed to increase shared memory limits"
-
             # Configure passwordless sudo for ec2-user
             echo "ec2-user ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ec2-user
             check_status "Failed to configure passwordless sudo for ec2-user"
@@ -198,7 +191,6 @@ Resources:
             check_status "Failed to create directories"
 
             
-            
             # Mount NFS volumes
             echo "sudo mount -t nfs $fsxNFSIP:$fsxdatamountpoint /$fsxdatavolumename"
             sudo mount -t nfs $fsxNFSIP:$fsxdatamountpoint /$fsxdatavolumename
@@ -219,14 +211,29 @@ Resources:
             sudo -u postgres /usr/bin/initdb -D /$fsxdatavolumename
             check_status "Failed to initialize PostgreSQL database cluster on FSxN volume"
 
+            # Increase shared memory limits
+            echo "kernel.shmmax = 68719476736" | sudo tee -a /$fsxdatavolumename/postgresql.conf
+            echo "kernel.shmall = 4294967296" | sudo tee -a /$fsxdatavolumename/postgresql.conf
+            sudo sysctl --system
+            
+            check_status "Failed to increase shared memory limits"
+
+            # Increase shared buffer in postgresql.conf
+            sudo sed -i "s|^shared_buffers =.*|shared_buffers = 4GB|" /$fsxdatavolumename/postgresql.conf
+
+            # Increase work_mem in postgresql.conf
+            sudo sed -i "s|^#work_mem =.*|work_mem = 32MB|" /$fsxdatavolumename/postgresql.conf
+
             # Update PostgreSQL configuration to use the new data and log directories
             sudo sed -i "s|^#data_directory =.*|data_directory = '/$fsxdatavolumename'|" /$fsxdatavolumename/postgresql.conf
             sudo sed -i "s|^#log_directory =.*|log_directory = '/$fsxlogvolumename'|" /$fsxdatavolumename/postgresql.conf
             check_status "Failed to update PostgreSQL configuration"
 
-            # Initialize database
-            sudo /usr/bin/postgresql-setup --initdb
-            check_status "Failed to initialize PostgreSQL service"
+            # Change the PGDATA environment variable
+            sudo sed -i "s|^Environment=PGDATA=.*|Environment=PGDATA=/$fsxdatavolumename|" /usr/lib/systemd/system/postgresql.service
+
+            # Reload the systemd configuration
+            sudo systemctl -p
 
             # Enable the PostgreSQL service to start on boot
             sudo systemctl enable postgresql
@@ -239,7 +246,6 @@ Resources:
             # Verify the installation
             sudo -u postgres /usr/bin/psql -c "SELECT version();"
             check_status "Failed to verify PostgreSQL installation"
-
             
 
             # Switch to postgres user and move wal logs to log volume
@@ -266,13 +272,13 @@ Resources:
             check_status "Failed to list databases"
 
             # Verify the data directory
-            #data_directory=$(sudo -u postgres /usr/bin/psql -t -c "SHOW data_directory;" | xargs)
-            #if [ "$data_directory" = "/$fsxdatavolumename" ]; then
-                #echo "PostgreSQL data directory is correctly set to the FSxN mounted volume: $data_directory"
-            #else
-                #echo "Error: PostgreSQL data directory is not set to the FSxN mounted volume. Current data directory: $data_directory"
-                #exit 1
-            #fi
+            data_directory=$(sudo -u postgres /usr/bin/psql -t -c "SHOW data_directory;" | xargs)
+            if [ "$data_directory" = "/$fsxdatavolumename" ]; then
+                echo "PostgreSQL data directory is correctly set to the FSxN mounted volume: $data_directory"
+            else
+                echo "Error: PostgreSQL data directory is not set to the FSxN mounted volume. Current data directory: $data_directory"
+                exit 1
+            fi
 
             # Install dependencies for pgvector
             sudo yum install -y git gcc make libpq-devel
