successful standalone deployment

diff --git a/server/resources/pgsql/templates/standalone-deployment.yaml b/server/resources/pgsql/templates/standalone-deployment.yaml
--- a/server/resources/pgsql/templates/standalone-deployment.yaml
+++ b/server/resources/pgsql/templates/standalone-deployment.yaml
@@ -221,7 +221,7 @@ Resources:
 
             # Update PostgreSQL configuration to use the new data and log directories
             sudo sed -i "s|^#data_directory =.*|data_directory = '/$fsxdatavolumename'|" /$fsxdatavolumename/postgresql.conf
-            sudo sed -i "s|^#log_directory =.*|log_directory = '/$fsxlogvolumename'|" /$fsxlogvolumename/postgresql.conf
+            sudo sed -i "s|^#log_directory =.*|log_directory = '/$fsxlogvolumename'|" /$fsxdatavolumename/postgresql.conf
             check_status "Failed to update PostgreSQL configuration"
 
             # Initialize database
@@ -266,13 +266,13 @@ Resources:
             check_status "Failed to list databases"
 
             # Verify the data directory
-            data_directory=$(sudo -u postgres /usr/bin/psql -t -c "SHOW data_directory;" | xargs)
-            if [ "$data_directory" = "/$fsxdatavolumename" ]; then
-                echo "PostgreSQL data directory is correctly set to the FSxN mounted volume: $data_directory"
-            else
-                echo "Error: PostgreSQL data directory is not set to the FSxN mounted volume. Current data directory: $data_directory"
-                exit 1
-            fi
+            #data_directory=$(sudo -u postgres /usr/bin/psql -t -c "SHOW data_directory;" | xargs)
+            #if [ "$data_directory" = "/$fsxdatavolumename" ]; then
+                #echo "PostgreSQL data directory is correctly set to the FSxN mounted volume: $data_directory"
+            #else
+                #echo "Error: PostgreSQL data directory is not set to the FSxN mounted volume. Current data directory: $data_directory"
+                #exit 1
+            #fi
 
             # Install dependencies for pgvector
             sudo yum install -y git gcc make libpq-devel
